function errorFeatures = extractErrorFeatures(results)
% function errorFeatures = extractErrorFeatures(results) 
% extract features which can be used for error analysis.
%
% INPUT
% - results: MAS analysis results of Sit-to-Stand test.
% OUTPUT
% - errorFeatures: feature sets which to be used in anomalyDetection.
% 
% HISTORY
% 2019/05/20 modified so that mainStruct and result will be taken as
% arguments.
% 2019/01/03 functionized.
% 
% AUTHOR
% Aki Kunikoshi
% a.kunikoshi@gmail.com
%

settings_Sit2Stand;


%% load signal
signal = [results.report.velocityVT, ...
    results.report.angle];
phases = results.report.phases;
phaseNumMax = size(phases, 1);
 
% as of the Slack message from Bas on 2018/11/29.
% phases
%   col 1: start SiSt
%   col 2: max flex SiSt
%   col 3: end SiSt
%   col 4: start StSi
%   col 5: max flex StSi
%   col 6: end StSi
%   col 7&8: (Bas added personally. Not required for this topic).
SiStStart = phases(:, 1);
SiStEnd   = phases(:, 3);
% StSiStart = phases(:, 4);
% StSiEnd   = phases(:, 6);


%% error features
SiSt = results.database.SitToStand;
StSi = results.database.StandToSit;

X = [];
for p = 1:phaseNumMax
    similarity = [];
    for axisNum = 1:size(signal, 2)
        similarity_ = getSignalSimilarity(...
            signal(SiStStart(1):SiStEnd(1), axisNum), ...
            signal(SiStStart(p):SiStEnd(p), axisNum));
        similarity = [similarity, similarity_];
    end
    clear axisNum similarity_
    
    X = [X; ...
        SiSt.total_duration(p), ...
        SiSt.flexion_duration(p), ...
        SiSt.extension_duration(p), ...
        SiSt.stand_duration(p), ...
        SiSt.maximum_flexion_angular_velocity(p), ...
        SiSt.maximum_extension_angular_velocity(p), ...
        SiSt.flexion_range(p), ...
        SiSt.extension_range(p), ...
        SiSt.maximum_vertical_velocity(p), ...
        SiSt.mean_power(p), ...
        SiSt.peak_power(p), ...
        SiSt.time_to_peak_power(p), ...
        SiSt.rate_of_power_development(p), ...
        SiSt.peak_rate_of_power_development(p), ...
        StSi.total_duration(p), ...
        StSi.flexion_duration(p), ...
        StSi.extension_duration(p), ...
        StSi.maximum_flexion_angular_velocity(p), ...
        StSi.maximum_extension_angular_velocity(p), ...
        StSi.flexion_range(p), ...
        StSi.extension_range(p), ...
        StSi.minimum_vertical_velocity(p), ...
        StSi.mean_power(p), ...
        StSi.peak_power(p), ...
        StSi.time_to_peak_power(p), ...
        StSi.rate_of_power_development(p), ...
        StSi.peak_rate_of_power_development(p), ...
        similarity
        ];
end
clear similarity

errorFeatures = X;